name: recommender_saver
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.3.0
  bloc: ^8.1.4
  equatable: ^2.0.5
  flow_builder: ^0.1.0
  flutter_bloc: ^8.1.6
  font_awesome_flutter: ^10.7.0
  authentication_repository:
    path: packages/authentication_repository
  form_inputs:
    path: packages/form_inputs
  formz: ^0.6.0
  google_fonts: ^4.0.0
  meta: ^1.7.0
  intl: ^0.19.0
  cloud_firestore: ^5.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.4.2
  get_it: ^7.7.0
  flutter_staggered_grid_view: ^0.7.0
  restart_app: ^1.2.1
  share_plus: ^10.0.2
  rebirth: ^1.0.2
  flutter_phoenix: ^1.1.1

dev_dependencies:
  bloc_test: ^9.0.0
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  mocktail: ^1.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/
